name: gitsyncmarks_app
description: GitSyncMarks mobile app - sync bookmarks from GitHub, open in browser.
author: Joe Mild
publish_to: 'none'
version: 0.2.0-beta.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
