name: gitsyncmarks
description: A cross-platform bookmark sync app for GitSyncMarks

publish_to: 'none'

version: 0.3.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.0.0
  file_picker: ^8.0.0
  share_plus: ^10.0.0
  receive_sharing_intent: ^1.8.0
  pointycastle: ^3.7.3
  uuid: ^4.2.2

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app_icon.png
